package testCases;

import org.testng.Assert;
import org.testng.annotations.Test;

import pageObjects.AccountRegistrationPage;
import pageObjects.HomePage;
import testBase.BaseClass;

public class TC001_AccountRegistration_Test extends BaseClass{
	
	@Test(groups = {"sanity","master"})
	public void verfiAccountRegistration()
	{
		try
		{
		logger.info("<-----TC001_AccountRegistration_Test script started from here----->");
		HomePage homePage = new HomePage(driver);
		logger.info("Click My account drop down");
		homePage.clickOnMyAccountDropDown();
		logger.info("Clicked on My account drop down");
		logger.info("Select Register account from drop down");
		homePage.clickOnRegisterOptionFromMyAccoutDropDown();
		logger.info("Selected Register account from drop down");
		
		AccountRegistrationPage acctRegisterPage = new AccountRegistrationPage(driver);
		logger.info("Enter customer details");
		acctRegisterPage.enterFirstName(generateRandomString().toUpperCase());
		acctRegisterPage.enterLastName(generateRandomString().toUpperCase());
		String autoGeneratedEmailAddress = generateRandomString()+"@gmail.com";
		System.out.println("autoGeneratedEmailAddress is - "+autoGeneratedEmailAddress);
		acctRegisterPage.enterMailID(autoGeneratedEmailAddress);
		acctRegisterPage.enterTelePhoneNumber(generateRandomPhoneNumber());
		String autoGeneratedPassword = generateAlphaNumericPassword();
		System.out.println("autoGeneratedPassword is - "+autoGeneratedPassword);
		acctRegisterPage.enterPassword(autoGeneratedPassword);
		acctRegisterPage.enterConfirmPassword(autoGeneratedPassword);
		acctRegisterPage.clickOnPrivacyPolicy();
		logger.info("Entered customer details");
		logger.info("Click on continue button");
		acctRegisterPage.clickOnContinueButton();
		logger.info("Clicked on continue button");
		logger.info("Validate the confirmation message");
		String confirmationMessage = acctRegisterPage.getConfirmationMessage();
		String expectedConfirmationMessage = "Your Account Has Been Created!";
		//String expectedConfirmationMessage = "Your Account Has Been Created";
		if(confirmationMessage.equals(expectedConfirmationMessage))
		{
			Assert.assertEquals(confirmationMessage, expectedConfirmationMessage);
			logger.info("Validated the confirmation message");
		}
		else
		{
			logger.error("The validation got failed");
			Assert.assertTrue(false);
		}
		}
		catch (Exception e)
		{
			logger.error("TC001_AccountRegistration_Test script got failed");
			logger.error(e.getMessage());
			Assert.assertTrue(false);
		}
		logger.info("<-----TC001_AccountRegistration_Test script ends here----->");
	}
	
}
